##################################################################################################
#  Bonjour
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: bonjour
  labels:
    app: bonjour
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: bonjour
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bonjour
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bonjour
        version: "0.0.1"
    spec:
      containers:
      - name:  nodejs
        image: bonjour:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
